### ISSUE TITLE
NumberWord mistake on 113386

### ISSUE THREAD

**Issue by cliffspradlin** [sublee/korean#16]
In [3]: korean.NumberWord(113386).read()
Out[3]: '십만삼천삼백팔십육'

Should be: 십**일**만삼천삼백팔십육

I know this library is not maintained, but it is still in pypi and has a very prominent package name "korean" so I thought it would be good to report this bug so that others can see.

**Comment by sublee** [comment]
Thank you for reporting the bug. I agree with you. I fixed the bug and release it as v0.1.9.

**Comment by cliffspradlin** [comment]
Wow, thank you @sublee  ! :)
