### ISSUE TITLE
(이)라 문제

### ISSUE THREAD

**Issue by pinkrespect** [sublee/korean#17]
`python 3.8` 환경에서 다음과 같은 코드를 실행하면

```python3
from korean import l10n, Noun

data = '{name:라}고' 
print(data.format(name=Noun('사')))  # 사라고
print(data.format(name=Noun('산')))  # 산라고
print(l10n.proofread('용사(이)라'))  #용사(이)라
```

주석에 넣은 것과 같은 내용으로 출력됩니다. 또한 `(이)라` 로 변경해 보면 `(이)가`로 출력됩니다.
어떤 부분을 수정하면 될 지 아직 실력이 모자라서 풀리퀘스트를 넣기 어려워 이슈에 남깁니다..

혹시라도 알려 주신다면 수정 후 풀리퀘스트 넣겠습니다.

좋은 오픈 소스 감사드려요.

**Comment by sublee** [comment]
이슈를 제보해주셔서 감사합니다. 죄송하게도 더는 이 프로젝트를 적극적으로 관리하지 않고 있습니다. [토씨](https://github.com/what-studio/tossi)를 대신 사용하길 권해드립니다. 토씨에는 활용형이 많은 서술격 조사 "(이)다"가 구현되어있습니다.
